Develop
King-Benx/my-portfolio pull request #1
Opened 2022-12-01 12:09 UTC by King-Benx

**Description**
This pull request delivers a simple mobile-first view of my portfolio.

**Deliverables in pr**
1. Mobile first look of portfolio
2. github workflows
3. Local linting

**How to test**
1. Clone repo using ```git clone git@github.com:King-Benx/my-portfolio.git```
2. Checkout to branch develop ```git checkout develop```
3. Run node modules ```npm i```
4. Run the application either using live server or right click file and open with your browser

**Screenshots**
![Screenshot 2022-12-01 at 2 51 21 PM](https://user-images.githubusercontent.com/17830204/205049102-28dc4c17-b3b6-4557-9e92-bd0e68955aec.png)

2022-12-01 13:00 UTC, Felix45 requested changes
Hi @King-Benx , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :heavy_check_mark: 
- [ ] Descriptive pull request summary :white_check_mark: 
- [ ] Good descriptive commit messages :white_check_mark: 
- [ ] All linter checks are set up and passing as expected :white_check_mark: 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 13:00 UTC, Felix45 commented on index.html
> +      </nav>
- [ ] Please consider wrapping this part of your webpage in a `header` tag since this part of your webpage is a page header. In most websites, the `logo` and the navigation are usually wrapped inside a `header` tag as a result of convention and User experience. 

- [ ] The text `Welcome` is supposed to be the logo of this webpage, as a convention, the logo needs to be wrapped inside of an `a` tag instead of a `span` tag. please consider wrapping the text `Welcome` in an `a` tag and also provide a link to the home page in its `href` attribute.

### Example code
```HTML
<header>
  <a href="index.html">Welcome </a>
  <nav>
    <img src="images/humbager.png" alt="humbager" />
  </nav>
</header>
```
- [ ] Please also make sure that your `margins` and `padding` are consistent with the Figma design. The margins on the header part of your design are not consistent with the Figma template. Please see the screenshot below.

## Your Implementation
<img src="https://user-images.githubusercontent.com/16392046/205057250-96309f95-cd3d-4e95-a9aa-f6a977212222.png" width="375px" />

## Figma template 
![Template 3-main-mobile](https://user-images.githubusercontent.com/16392046/205057978-09c7a390-dd2a-4c81-964a-d636d7ad9b9f.png)

2022-12-01 13:00 UTC, Felix45 commented on index.html
> +      </header>
- [ ] Please consider changing this `header` tag to a `section` tag, semantically this part of the webpage is not a `header` but rather a generic standalone section of a document thus the `section` tag would be the most suitable tag for it. For more details please see this [link >>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)

2022-12-01 13:00 UTC, Felix45 commented on index.html
> +          </div>
- [ ] Please consider wrapping the social media list of icons in a `ul` tag instead of the generic `div` tag and that all `a` tags are wrapped in a `li` tag. Since this is a listing of social media icons it's semantically correct to wrap them in a `ul` tag.

2022-12-02 04:16 UTC, King-Benx commented on index.html
> +      </nav>
This has been resolved

2022-12-02 04:16 UTC, King-Benx commented on index.html
> +      </header>
This has been resolved

2022-12-02 04:17 UTC, King-Benx commented on index.html
> +          </div>
This has also been resolved

2022-12-02 04:54 UTC, binhussen approved these changes
Hi @King-Benx , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions
- [optional] kindly, follow semantic rules for readability and search engines.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 04:54 UTC, binhussen commented on index.html
> +        </button>
- [Optional] I Think it is better to make the hamburger button inside a `<nav>` tag for semantics reasons. 👍 👍

2022-12-02 05:47 UTC, merged